version: '2'
services:
    apmbackoffice-app:
        image: apmbackoffice
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://apmbackoffice-postgresql:5432/apmBackoffice
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8090:8090
    apmbackoffice-postgresql:
        extends:
            file: postgresql.yml
            service: apmbackoffice-postgresql
